version: '3.11'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  api:
    build: ../t3_fastApi/
    command: "poetry run uvicorn main:app --host 0.0.0.0 --port 80"
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "80:80"
